### PR TITLE
~ Temp fix for bad input in sizes

### PR DESCRIPTION
**Pull request by mobilarte**
If user leaves a space in size input, generate cutlist fails without message. This fix prepares for better sanitizing of input values.

### CODE REVIEW

**Comment by bbeaulant** [comment]
This works only for metric size, no ?
Because if a dimension is fractional in inch, the space character is allowed.

**Comment by mobilarte** [comment]
You are right, it is not only allowed but IT must be present, 1 3/4 != 13/4. Nevertheless, we should check input, because it really badly fails in ruby `material_attributes.rb:95:in 'to_l'`.

Shall I open an issue, so that it can be fixed later?

**Comment by bbeaulant** [comment]
Yes, it mays be a good thing to open an issue. In this case, I can keep it in mind ;)
I think the best way to solve input check is to write special input field for sizes. This field can contains a text field for value and a select for unit. In this case, no check of the unit but easier unit dependent check of the value.

**Comment by mobilarte** [comment]
Closing pull request, instead issue has been filed.

**Pull request closed without merging**
