### PR TITLE
I18n update

### PR DESCRIPTION
**Pull request by mobilarte**

### CODE REVIEW

**Comment by bbeaulant** [comment]
Hi @mobilarte, thanks for these translations. But as I can understand translated sentences it refer to a general modification of the instance against its definition.

The information that this message must show it that the instance is **resized**, not modified.

It would be better to use "resized" instead od "modified", no ?

**Comment by mobilarte** [comment]
You are right, I will commit the change and make a pull request later this evening.

**Comment by mobilarte** [comment]
Changed to make clear that the modification affects size only in en/de

**Comment by bbeaulant** [comment]
Nice, thank you !

**Pull request merged**
